language: c
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libsdl1.2-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl; fi
script:
  - autoreconf -i
  - mkdir -p build
  - cd build
  - sh ../configure
  - make
notifications:
  email:
    on_success: change
    on_failure: change