language: c
os:
  - linux
  - osx
matrix:
  include:
    - os: linux
    - os: linux
      dist: trusty
    - os: osx
      osx_image: beta-xcode6.1
    - os: osx
      osx_image: beta-xcode6.2
    - os: osx
      osx_image: beta-xcode6.3
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode7
    - os: osx
      osx_image: xcode7.1
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8
addons:
  apt:
    packages:
      - libsdl1.2-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl; fi
  - wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh
  - wget https://raw.githubusercontent.com/dansoton/assert.sh/assert-extras/assert-extras.sh
  - source assert.sh
  - source assert-extras.sh
script:
  - autoreconf -i
  - mkdir -p build
  - cd build
  - sh ../configure
  - make
  - assert_startswith "./schismtracker --version" "Schism Tracker"
  - assert_end tests
notifications:
  email:
    on_success: change
    on_failure: change