environment:
    matrix:
    - arch: i686
      bits: 32
    - arch: x86_64
      bits: 64

cache:
  - 'C:\msys32'

install:
  - ps: |
      [Environment]::SetEnvironmentVariable("MSYS2_PATH_TYPE", "inherit", "Machine")
      $arch = $env:Arch
      $bits = $env:Bits
      $msys = "msys$bits"
      $mingw = "mingw$bits"
      $mingwUpper = $mingw.ToUpper()
      $folder = $env:APPVEYOR_BUILD_FOLDER

      $env:PATH="C:\$msys\$mingw\bin;C:\$msys\usr\bin;$env:PATH"

      function bash($command, $dieOnError = $true) {
        ""
        Write-Host $command

        $folder = $folder -Replace '\\', '/'

        & "C:\$msys\usr\bin\sh.exe" --login -c "MSYSTEM=$mingwUpper . /etc/profile && cd $folder && $command"

        if ($LASTEXITCODE -eq 0) {
          Write-Host "'$command' succeeded. While its output might be red, it exited with '0'." -ForegroundColor Green
        } else {
          Write-Host "'$command' failed with exit code $LASTEXITCODE! " -ForegroundColor Red -NoNewline

          if ($dieOnError) {
            Write-Host "Exiting." -ForegroundColor Red
            exit $LASTEXITCODE
          } else {
            "Continuing."
          }
        }
      }

      # 32-bit MSYS2 is not offered on AppVeyor yet, so we need to install it.
      if ($arch -eq "i686") {
        Write-Host "Installing 32-bit MSYS2..." -ForegroundColor Cyan

        # download installer
        $zipPath = "$($env:USERPROFILE)\msys2-i686-latest.tar.xz"
        $tarPath = "$($env:USERPROFILE)\msys2-i686-latest.tar"

        "Downloading MSYS2 installation package..."
        (New-Object Net.WebClient).DownloadFile('http://repo.msys2.org/distrib/msys2-i686-latest.tar.xz', $zipPath)

        Write-Host "Unzipping $zipPath..."
        7z x $zipPath -y -o"$env:USERPROFILE" | Out-Null

        Write-Host "Untaring $tarPath to C:\msys32\..."
        7z x $tarPath -y -oC:\ | Out-Null
        del $zipPath
        del $tarPath

        Write-Host "32-bit MSYS2 installed" -ForegroundColor Green

        bash "pacman --sync --noconfirm --needed pacman pacman-mirrors"
        bash "pacman --sync --noconfirm --needed VCS"
        bash "pacman --sync --noconfirm --needed base-devel"
        bash "pacman --sync --noconfirm --needed msys2-devel"
        bash "pacman --sync --noconfirm --needed mingw-w64-$arch-toolchain"
      }

      bash "pacman --sync --noconfirm --needed mingw-w64-$arch-SDL"

build_script:
  - ps: |
      bash "autoreconf --install --include=/$mingw/share/aclocal/"
      bash "./configure"
      bash "make"

on_failure:
  - if exist "config.log" 7z a schismtracker_debug_logs.7z "config.log" > nul
  - if exist "configure.ac" 7z a schismtracker_debug_logs.7z "configure.ac" > nul
  - if exist "configure" 7z a schismtracker_debug_logs.7z "configure" > nul
  - if exist "C:\msys%bits%\mingw%bits%\bin\sdl-config" 7z a schismtracker_debug_logs.7z "C:\msys%bits%\mingw%bits%\bin\sdl-config" > nul

on_finish:
  - if exist schismtracker_debug_logs.7z appveyor PushArtifact schismtracker_debug_logs.7z
  - if exist schismtracker.exe appveyor PushArtifact schismtracker.exe

artifacts:
  - path: '*.7z'

notifications:
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true