environment:
    matrix:
    - platform: x86
      arch: i686
      mingw: mingw32
      msys: msys32
    - platform: x64
      arch: x86_64
      mingw: mingw64
      msys: msys64

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true