#ifndef DEFINES_H
#define DEFINES_H

#define WIDESCREEN_WIDTH 1920
#define WIDESCREEN_HEIGHT 1080
#define WIDESCREEN_CHARS_WIDTH (WIDESCREEN_WIDTH / 8)
#define WIDESCREEN_CHARS_HEIGHT (WIDESCREEN_HEIGHT / 8)

#endif // DEFINES_H
